### ISSUE TITLE
Advanced Reactorでの加工の際，液体辞書で対応した別の液体を用いるとクラッシュする

### ISSUE THREAD

**Issue by Hiiragi283** [SkyTheory/HeatAndProcessing#10]
v1.3.7においてAdvanced Reactorを使用する際，液体辞書で対応した別の液体（例. `dcs.steam`が要求されているところ，代わりに`steam`を入れる）で加工すると完成時にクラッシュし，二度とワールドに入ることができなくなってしまいました。

[こちら (GOHDのissue tracker) ](https://github.com/Hiiragi283/Good-Old-Halcyon-Days/issues/32)にその詳細があります。
もしかするとHaP単体では起こらない可能性もありますが，念のため報告しておきました。

**Comment by SkyTheory** [comment]
ありがとうございます。原因が特定できましたので、バージョン1.3.8にて液体消費処理及びチェック処理を変更しておきました。
