### ISSUE TITLE
Baublesインベントリのアクセサリが機能しない

### ISSUE THREAD

**Issue by K-ebisen** [SkyTheory/HeatAndProcessing#2]
ver.1.0.4にて、Baublesインベントリに装備したHaC本体のアクセサリが機能していません。
ver.1.0.3では正常に動作しているため、HaC本体やBaubles側は原因でないと判断しこちらに報告させていただきました。

**Comment by SkyTheory** [comment]
報告ありがとうございます。確かにこちらの処理が原因ですね、申し訳ありません。修正版を1.0.5としてリリースしました。
