### ISSUE TITLE
Advanced Reactorが低トルク帯で機能しない

### ISSUE THREAD

**Issue by K-ebisen** [SkyTheory/HeatAndProcessing#3]
Advanced Reactorに入力されるトルクが64を僅かでも下回った場合、動作が完全に停止します。ver.1.0.3と1.0.4で共通です。
なおHaC本体のトルクマシンでは、tier3のマシンにトルク1桁を入力した場合でも極低速ながら動作します。

**Comment by SkyTheory** [comment]
そちらは仕様ですが、ガイド漏れですね。Advanced ReactorはHeatTierの調節機能がある代わりに64.0f以上のトルクを要求する、という設計になっています。次回更新時にTipsに追加しようと思います。
