### ISSUE TITLE
Advanced Reactor使用時にサーバーから切断される場合がある

### ISSUE THREAD

**Issue by K-ebisen** [SkyTheory/HeatAndProcessing#5]
Advanced Reactor使用時、稀にサーバーから切断されます(シングルプレイです)。
曖昧な報告で恐縮ですが、発生したのはいずれもGUIを触っている時…だったと記憶しております。

現象が発生した時刻のログがこちらです。これより前はAromaBackupが続いておりました。
https://pastebin.pl/view/a1290a24

導入MOD一覧はこちらです。
https://pastebin.pl/view/7886e972

**Comment by SkyTheory** [comment]
報告ありがとうございます。開発環境でも発生したので、調査してみます。

**Comment by SkyTheory** [comment]
原因の特定には至っておりませんが、関連の疑いのある処理を若干変更しました。（ラグが強い等の限定的な状況でのみ起こり得るような処理が原因であるならばこれからも発生しそうですが……）modの更新をお願いします。

**Comment by K-ebisen** [comment]
対応ありがとうございます。更新させていただいたので、様子を見てみます。
