### ISSUE TITLE
Advanced Reactorの中身がリセットされる

### ISSUE THREAD

**Issue by K-ebisen** [SkyTheory/HeatAndProcessing#6]
ver.1.1.0以降、ワールドを終了する(もしくはワールドを読み込む？)際にAdvanced Reactorの中身がフィルターや温度の設定まで含め全てリセットされます。

**Comment by SkyTheory** [comment]
恐らく原因は切断される場合があるというissueと同じものかと思います。こちらの問題については開発環境内で発生を確認できず、最新バージョンにおいて同様の現象が発生した場合は原因の特定を開始しようと思います。（一応、確証はありませんが関連のありそうな処理を変更した前提modを本日中にリリースする予定です）
どうやらNBTの読み書きが原因のようですので、もし他のワールドで設置したAdvanced Reactorでは発生しないようであるならば、当該ブロックを破棄、新しいものを設置しなおすという形で解決するかとは思います。

**Comment by K-ebisen** [comment]
対応ありがとうございます。既存のブロックでも正常に動作するようになりました。
