### ISSUE TITLE
コンフィグの内容によって起動時にクラッシュする / crashing on startup

### ISSUE THREAD

**Issue by K-ebisen** [SkyTheory/HeatAndProcessing#7]
~~ver.1.2.0導入時、古いコンフィグファイル(恐らくリリース当初のもの？)が残っているとクライアント起動時にクラッシュしました。~~
~~単純に該当のファイルを削除するだけで解決しましたが、今後同様の症状が出た方がいた場合のために一応ここに報告という形で記録を残しておきます。~~
訂正します。コンフィグのB:AutoHideHUDがfalseの場合にクラッシュするようです。

The client crashes on startup with ver.1.2.0.
~~Deleting old-config-files will solve this problem.~~
Setting ''B:AutoHideHUD=true'' will solve this problem.

**Comment by SkyTheory** [comment]
報告ありがとうございます。原因が判明したので修整しました。

**Comment by K-ebisen** [comment]
対応ありがとうございます…が、どうも修正されていないようです。
ver.1.2.2にて、プレイしている構成に加えて最小構成でも確認しております。

**Comment by SkyTheory** [comment]
ううむ……こちらの環境では起動に成功しているのですが、環境に依るような動作が原因なのかもしれません。クラッシュを発生させているコードに検討はついていますので、次回の更新でその辺りの処理を変更（具体的には、コンフィグの読み込みをASMとそれ以外で完全に分割）しようと思います。

**Comment by SkyTheory** [comment]
すみません。modの構成を変えた、実行環境（開発環境ではなく）で発生を確認しました。
明日辺りで修正版を上げる予定です。少々お待ちください。
