### ISSUE TITLE
[Suggestion] Adding a machine to buy/sell items using the MCEconomy3 API

### ISSUE THREAD

**Issue by gatoborrachon** [SkyTheory/HeatAndProcessing#8]
**Proposed Idea**
+(As the title says,) Implement a machine where you can do transactions (Buy/Sell) with the items of Heat and Climate 

**Details of the Idea**
+As these items already have [Compatibility](https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/java/defeatedcrow/hac/plugin/DCPluginMCE.java) with the [MCEconomy3 API](https://github.com/shift02/MCEconomy3), all should be done instantly once this supposed machine can read all the Buy/Sell orders

**Additional Notes**
+Back in 1.7.10, specifically with the mods SextiarySector2 and MCEconomy2, there used to be a thing called  the "Creeper Shop", which required energy and was necessary to buy/sell things, in this case, there were things that you can get only in the Creeper Shop (A nice idea if you ask me), but since there's not SextiarySector for 1.12, it is not possible to implement a system similar to this one ()

-Even when the Github Page of MCEconomy3 says that it is fo 1.10, the [build.gradlew file says that it is fo 1.12](https://github.com/shift02/MCEconomy3/blob/aa67ab2944bafcd421a2306b594223891d83cf2c/build.gradle#L38), i already tested this and it seems to work fine, at least with the little implementation that MCEconomy3 has (Showing the MP (Minecraft Points) Value of the items that are registered)

-If you don't like the idea, feel free to close the issue

**Comment by SkyTheory** [comment]
Thank you. However, in doing so I have the problem of not being able to balance the game as I see fit.
I do not intend to implement it at this time.

**Comment by gatoborrachon** [comment]
No problem, thanks for the answer
