### ISSUE TITLE
[Suggestion] Increase the size of the internal tanks of the Advanced Reactor

### ISSUE THREAD

**Issue by gatoborrachon** [SkyTheory/HeatAndProcessing#9]
**Idea**
This would let modpackers to add advanced recipes (recipes that use more than 4,000 mb of a fluid) that will require this tier of Chemical Reactor

**Additional Notes**
Also, sorry for asking this, but how exactly work the Fluid Ports? i followed the example pic in the CurseForge page of the mod, but i can't introduce liquids in these ports

-In this screenshot, you can see how the 2 pipes have a fluid, but the fluid can't enter to the Fluid Port
![2021-12-23_18 56 27](https://user-images.githubusercontent.com/61126174/147303297-e13396c4-b040-4b56-9e0c-529c61550e4e.png)

**Comment by SkyTheory** [comment]
As for that idea, I think it can be realized by increase the value per mb of liquid or recipes required higher tier materials.
The Reactor Fluid Port transfers liquid to and from adjacent tanks. The pipes should not be connected directly to each other, but should be buffered.
The top is for insertion and the bottom is for extraction. The back works as both.

**Comment by gatoborrachon** [comment]
Let me try it, thanks
